### ISSUE TITLE
GenerateKey issue

### ISSUE THREAD

**Issue by torresdavida** [emitter-io/csharp#5]
I'm trying to generate a key using...
```
                emitter.GenerateKey(
                    secretKey,
                    channelName,
                    EmitterKeyType.ReadWrite,
                    keygen =>
                    {
                        channelKey = keygen.Key;
                        Console.WriteLine("Generated Key: " + keygen.Key);
                    });
```
And these lines are never executed to return a new key.

```
                        channelKey = keygen.Key;
                        Console.WriteLine("Generated Key: " + keygen.Key);
```

I can create a channel key in the emitter.io console and the code works fine... but I need to be able to generate channels on the fly.

[Program.cs.txt](https://github.com/emitter-io/csharp/files/2517129/Program.cs.txt)

**Comment by Florimond** [comment]
I'm afraid the documentation is not very clear on that topic, but you channel name is required to end with "/". I'm pretty sure that's the issue here. Don't forget you can also use wildcards. Have a look at the documentation at the bottom of this page for more information https://emitter.io/develop/message-filtering/

**Comment by torresdavida** [comment]
That was the issue, my apologies for the false alarm, thought for sure I had covered that issue.
